services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppass"]
      interval: 5s
      retries: 5
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DB_DSN: "user:pass@tcp(db:3306)/snippetbox?parseTime=true"
volumes:
  db-data: