name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: snippetbox
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uuser -ppass"
          --health-interval=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        run: |
          go mod tidy
          go build -o snippetbox ./cmd/web
      - name: Docker Build
        run: docker build -t snippetbox .
      - name: Test Container
        run: |
          docker run --rm -d -p 4000:4000 \
            --env DB_DSN="user:pass@tcp(127.0.0.1:3306)/snippetbox?parseTime=true" \
            snippetbox
          sleep 10
          curl -f http://localhost:4000
      - name: Docker Push
        run: echo "Push to registry here (e.g., Docker Hub, GHCR)"